formatter: markdown

output:
  file: README.md
  mode: replace
  template: |-
    ## terraform-aws-secretsmanager
    Terraform module to provision and manage AWS Secrets Manager.

    ## Usage

    ```hcl
    module "label" {
      source  = "cloudposse/label/null"
      version = "0.24.1"

      name      = "alpha"
      namespace = "so"
      stage     = "staging"
    }

    module "ssh_key_pair" {
      source  = "cloudposse/key-pair/aws"
      version = "0.18.1"

      ssh_public_key_path = "keys/"
      generate_ssh_key    = "true"

      context = module.label.context
    }

    module "secrets" {
      source  = "SweetOps/secretsmanager/aws"
      version = "0.1.0"

      secret_version = {
        secret_string = jsonencode(
          {
            ssh_public_key  = base64encode(module.ssh_key_pair.public_key)
            ssh_private_key = base64encode(module.ssh_key_pair.private_key)
          }
        )
      }

      context = module.label.context
    }
    ```

    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS --> 

    ## License
    The Apache-2.0 license

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true