name: Sync labels

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labels.yml"

jobs:
  sync-labels:
    name: Sync labels in the declarative way
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          dry-run: ${{ github.event_name == 'pull_request' }}
