name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        if: "!contains(github.event.head_commit.message, '[skip-release]')"
        uses: release-drafter/release-drafter@v6
        with:
          publish: true
          prerelease: false
          config-name: auto-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
